import os
import time
import datetime
import requests
import pytest


@pytest.mark.integration
def test_alertmanager_delivers_to_estou_aqui():
    """E2E: postar alerta no AlertManager e validar entrega ao backend 'Estou Aqui'."""
    homelab = os.environ.get("HOMELAB_HOST", "127.0.0.1")

    alert = [
        {
            "labels": {"alertname": "IntegrationTestAlert", "severity": "warning", "instance": "test-runner", "service": "homelab-advisor"},
            "annotations": {"summary": "Integration test alert", "description": "Generated by pytest"},
            "startsAt": datetime.datetime.utcnow().isoformat() + "Z"
        }
    ]

    # Post to AlertManager API
    am_url = f"http://{homelab}:9093/api/v1/alerts"
    r = requests.post(am_url, json=alert, timeout=5)
    r.raise_for_status()

    # Esperar entrega e checar backend (/api/alerts/active)
    deadline = time.time() + 20
    backend_urls = [f"http://{homelab}:3000/api/alerts/active", f"http://{homelab}:3456/api/alerts/active"]
    while time.time() < deadline:
        for url in backend_urls:
            try:
                a = requests.get(url, timeout=5)
            except requests.RequestException:
                continue

            # Some environments serve the SPA on :3000 via nginx — prefer a JSON response from the API port
            content_type = a.headers.get('Content-Type', '')
            if 'application/json' not in content_type:
                continue

            payload = a.json()
            names = [al.get('name') for al in payload.get('alerts', [])]
            if 'IntegrationTestAlert' in names:
                return
        time.sleep(1)

    pytest.fail('AlertManager -> Estou Aqui delivery failed: alert not found in /api/alerts/active (tried ports 3000 and 3456)')
